# Generated by Django 4.0.3 on 2022-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('article_link', models.URLField(null=True)),
                ('publish_date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
