# Generated by Django 4.0.3 on 2022-03-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
